[package]
name = "cinnabar"
version = "0.0.1"
compiler = "0.14.2"
repository = "https://github.com/lvyuemeng/cinnabar"
entrypoint = "lib.typ"
authors = ["lvyuemeng <lv15623448685@gmail.com>"]
license = "MIT"
description = "Composable primitives for Chinese formal documents."
keywords = ["chinese", "thesis", "academic", "components", "中文", "论文"]
categories = ["office"]
exclude = ["example/", "img/", "docs/"]
